### ISSUE TITLE
图片名带点，会导致点后面的识别为类型。还有图片名太长了。

### ISSUE THREAD

**Issue by linonetwo** [tiddly-gittly/Browser-Extension-Tiddlywiki-Collector#10]
https://www.linkedin.com/pulse/hudson-trade-capture-new-trading-platform-troy-peterson

![截屏2023-12-17 14 21 20](https://github.com/tiddly-gittly/Browser-Extension-Tiddlywiki-Collector/assets/3746270/0519d98b-5f50-43a9-adbc-135500b32039)
![截屏2023-12-17 14 05 18](https://github.com/tiddly-gittly/Browser-Extension-Tiddlywiki-Collector/assets/3746270/6d537bba-ec8c-44af-9926-98e2fd803d2f)

**Comment by oeyoews** [comment]
剪藏的标题下划线可以换成空格, 下划线太多了
