### ISSUE TITLE
一些小的问题记录

### ISSUE THREAD

**Issue by oeyoews** [tiddly-gittly/Browser-Extension-Tiddlywiki-Collector#2]
- 多次检测同一个网页, 如果没有手动修改title, 会直接覆盖原有的tiddler, 有直接覆盖非剪藏的tiddler,比较危险(应该可以在保存前检测一下或者弹出警告)
- 选择对应的保存类型时 更新tiddler的类型(比如markdown比较受影响)
- tag打不上

> ps: 似乎已经有usememo的大致功能了

**Comment by linonetwo** [comment]
第一个还好，readability 检测出的标题都很长，基本不会冲突，另外两个修了

**Comment by linonetwo** [comment]
那不就是「加为书签」那个按钮吗

**Comment by linonetwo** [comment]
参考 https://github.com/tiddly-gittly/mobile-imessage-layout 做一个吧，或者就在这仓库里改这个

**Comment by linonetwo** [comment]
或者你来做个 https://github.com/rubickCenter/rubick 的插件吧，这个也是开源的

**Comment by oeyoews** [comment]
> 可以补一个 不进行剪切的选项, 使用时间戳充当标题
> 
> <img alt="image" width="524" src="https://private-user-images.githubusercontent.com/72405338/275488346-d74c4f18-b36e-48c9-8161-60569cce053a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMjc5ODIsIm5iZiI6MTcxMTEyNzY4MiwicGF0aCI6Ii83MjQwNTMzOC8yNzU0ODgzNDYtZDc0YzRmMTgtYjM2ZS00OGM5LTgxNjEtNjA1NjljY2UwNTNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDE3MTQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5MTg1YTY3NjliZGY2MDg0YTBlYWJmZWZjY2NkZTQwNGFiMDI1YmM3ZjI2ODQ5ZTZmZDVhYjZiMWM2YmUxY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M_xfToXquDWEao94tyzM9i375T6bUJdBFZ5NaY-RZzI">

用 vue 重写了之前的 usewiki 浏览器扩展， 支持了剪切到tiddlywiki和保存markdown到本地了

<img width="663" alt="image" src="https://github.com/tiddly-gittly/Browser-Extension-Tiddlywiki-Collector/assets/72405338/99809451-b9fb-4e25-98a8-cbc19804a414">
