### ISSUE TITLE
支持在线托管的nodejs  wiki

### ISSUE THREAD

**Issue by oeyoews** [tiddly-gittly/Browser-Extension-Tiddlywiki-Collector#5]
对于托管的nodejs wiki, 可能需要处理验证这一块

**Comment by linonetwo** [comment]
用户名密码的基本验证啊，这的确还没有

**Comment by oeyoews** [comment]
我看官方的文档(webserver api), 好像不支持这一点

**Comment by linonetwo** [comment]
用的都是官方的 API

**Comment by oeyoews** [comment]
https://github.com/Jermolene/TiddlyWiki5/blob/17665233a29bca9c0bfe9578cdac6ca1a6303f49/core/modules/server/authenticators/header.js 感觉有点迷

**Comment by oeyoews** [comment]
<img width="663" alt="image" src="https://github.com/tiddly-gittly/Browser-Extension-Tiddlywiki-Collector/assets/72405338/c9d0a4ec-88c2-4772-925c-de69aaf7271c">  好像少了关键的一步

**Comment by linonetwo** [comment]
没用过，还不如等待以后有人搞个正经登录，例如 https://github.com/linonetwo/try-passportjs-gitlab-tiddlywiki

**Comment by oeyoews** [comment]
https://github.com/oeyoews/usewiki2/issues/15#issuecomment-2211004637 其实 tiddlywiki 的几个saver 里面也有对应的例子
