### ISSUE TITLE
部分网页仅显示html text 文件类型的tab, 没有markdown/wikitext

### ISSUE THREAD

**Issue by oeyoews** [tiddly-gittly/Browser-Extension-Tiddlywiki-Collector#7]
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array/toLocaleString

**Comment by linonetwo** [comment]
应该再点开一次就好了，我也忘了这是为啥，可能是因为 html 没加载完吧

**Comment by oeyoews** [comment]
<img width="555" alt="image" src="https://github.com/tiddly-gittly/Browser-Extension-Tiddlywiki-Collector/assets/72405338/4ee61ee2-25b7-4f0e-bf68-12462c089810">

好像是 html2md 不支持table 的节点

**Comment by oeyoews** [comment]
手动 把table 的节点删除后就可以了

**Comment by oeyoews** [comment]
https://unifiedjs.com/learn/recipe/remark-table/ table 需要remark-gfm插件来支持

**Comment by oeyoews** [comment]
> https://unifiedjs.com/learn/recipe/remark-table/ table 需要remark-gfm插件来支持

尝试加上remark-gfm插件后, 打包会出现错误, 是 https://github.com/crxjs/chrome-extension-tools 的问题吗

**Comment by linonetwo** [comment]
你咋装的，有 pnpm i 它吗

**Comment by oeyoews** [comment]
刚开始是加载到了remark-gfm的, 我刚才看了一下package.json文件里面没有更新上去, 可能是dprint 安装失败导致的

**Comment by linonetwo** [comment]
你看看还有啥插件要加的一起加了吧

**Comment by oeyoews** [comment]
dprint 的安装问题没解决掉, 应该是网络问题

<img width="836" alt="image" src="https://github.com/tiddly-gittly/Browser-Extension-Tiddlywiki-Collector/assets/72405338/78283ec1-0ed4-4b3b-9583-087d72d07f28">

**Comment by linonetwo** [comment]
给 shell 配个 http proxy 呗，或者看看能不能用阿里源

**Comment by oeyoews** [comment]
忘记v2raya 在windows 上不支持透明代理了, 设置了一下终端代理, ok了

**Comment by linonetwo** [comment]
别忘了 PR

**Comment by oeyoews** [comment]
https://github.com/tiddly-gittly/Browser-Extension-Tiddlywiki-Collector/pull/11 提过了

**Comment by linonetwo** [comment]
等我修了设置清空的问题发一版。tw5 typed 已经发了一版了
