### ISSUE TITLE
服务器配置一会儿会消失

### ISSUE THREAD

**Issue by linonetwo** [tiddly-gittly/Browser-Extension-Tiddlywiki-Collector#9]
可能是被重置了

**Comment by linonetwo** [comment]
<img width="982" alt="截屏2023-12-17 15 21 50" src="https://github.com/tiddly-gittly/Browser-Extension-Tiddlywiki-Collector/assets/3746270/0bf9b344-affb-4588-ad9c-a81d05529572">

我这页面开着，切别的页面一会儿不看它都能消失

**Comment by oeyoews** [comment]
应该是插件刷新了吧, options 页面就会被自动关掉

**Comment by oeyoews** [comment]
有时配置的服务器也会自动消失, 今天才发现, 不知道什么问题
